[package]
name = "bevy_ghx_utilities"
version = "0.1.0"
publish = false
description = "Internal utilities for examples"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.12.0", default-features = true }
