[package]
name = "bevy_ghx_proc_gen"
version = "0.1.0"
description = "Bevy plugin for 2D & 3D procedural generation with WFC/Model synthesis"
repository = "https://github.com/Henauxg/ghx_proc_gen"
documentation = "https://docs.rs/bevy_ghx_proc_gen"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "procedural", "wfc", "model synthesis", "bevy"]
categories = ["game-development", "algorithms"]
readme = "README.md"

[dependencies]
ghx_proc_gen = { path = "../ghx_proc_gen" }
bevy = { version = "0.12.0", default-features = true }
